### ISSUE TITLE
Release ZIPs generated from DoomLauncher crash on boot. Missing DLL?

### ISSUE THREAD

**Issue by robbinsrush** [hobomaster22/DoomLauncher#35]
So I got the zip generated in ReleaseBuild, and it popups the DOOM Launcher Logo before closing with no errors being shown. Upon copying "SQLite.Interop.dll" from x86 in one of the build folders (x64 didn't fix it), it boots successfully.

Additionally, this error pops up after cleaning the solution and running DoomLauncher as an x86 release. Not sure if it's entirely connected to the GameFiles directory being missing because it doesn't mention it in the error.

`code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: LaunchType
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at DoomLauncher.DataAccess.ExecuteSelect(String sql) in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Adapters\DataAccess.cs:line 31
   at DoomLauncher.DbDataSourceAdapter.GetSourcePorts() in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Adapters\DbDataSourceAdapter.cs:line 275
   at DoomLauncher.SettingsForm.PopulateDefaultSettings(IDataSourceAdapter adapter) in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Forms\SettingsForm.cs:line 164
   at DoomLauncher.SettingsForm..ctor(IDataSourceAdapter adapter, AppConfiguration appConfig) in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Forms\SettingsForm.cs:line 35
   at DoomLauncher.MainForm.ShowSettings(Boolean allowCancel, DialogResult& result) in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Forms\MainForm.cs:line 1001
   at DoomLauncher.MainForm.VerifyGameFilesDirectory() in C:\Users\Tony\Documents\DoomLauncher-master\DoomLauncher\Forms\MainForm_Init.cs:line 57`

P.S. I was able to reproduce the first issue on a second Windows 10 x64 machine.

**Comment by hobomaster22** [comment]
You have x86 and x64 build folders? Did you change any build settings? By default the project should build and work on any cpu and the System.Data.SQLite.dll should not require SQLite.Interop.dll. This is why it doesn't copy it over because it should not be required if the build is correct.

I played around with the settings and couldn't get it to build that way, trying to figure out how you got here.

**Comment by robbinsrush** [comment]
Do you build on x86, "Mixed Platforms," or "Any CPU?"

![image](https://user-images.githubusercontent.com/25468624/45259675-d1b3a100-b386-11e8-8803-dfe38f4e6d4d.png)

Building like this causes it on my machine.

In case you wanted to see, my NuGet package versions:

![image](https://user-images.githubusercontent.com/25468624/45259681-20f9d180-b387-11e8-8cef-2fb23c89f6d7.png)

**Comment by guynamederick** [comment]
Doom Builder is built on either "Mixed Platforms" or "Any CPU" (former preferred probably). x86 requires a dependency that shouldn't really be necessary, which is the SQLite.Interop.dll file. Your NuGet packages looks alright there.

**Comment by robbinsrush** [comment]
Well even when building on "Mixed Platforms" and "Any CPU," the DoomLauncher/bin/Debug/x86 folder still gets populated with SQLite.Interop.dll, and it's def. used by the program. The one in x64 doesn't get blocked when deleting so it's obviously not being used.

![image](https://user-images.githubusercontent.com/25468624/45260398-b606c580-b39b-11e8-8c03-8ce0f5ff28ac.png)

**Comment by hobomaster22** [comment]
Looking at this again, I think your NuGet packages are the issue. Sqlite was not added with the NuGet package manager. You have extra references to things that Doom Launcher doesn't really need like SQLite.Data.SQLiteCore which I think is creating your issue (the description has references to x86 and x64). The only thing that shows up in my NuGet packaged manager is the JSON library.

![packages](https://user-images.githubusercontent.com/42744211/45263827-20048680-b3ff-11e8-8a19-3470a13817a1.png)

Wondering if you did something to get those packages in there. Try deleting and getting a clean version and building?

**Comment by robbinsrush** [comment]
Apologies if I'm going about this wrong, I am not a C#/.NET programmer so I am simply cobbling together what I do know into this. 

Direct from your git:

![image](https://user-images.githubusercontent.com/25468624/45267052-2c4a0d00-b41a-11e8-9b4e-e54b01c4d621.png)

Missing all kinds of namespaces and packages.

Upon re-installing Newtonsoft.Json v9.0.1:

![image](https://user-images.githubusercontent.com/25468624/45267067-7af7a700-b41a-11e8-8bd6-d6ade1983aa5.png)

The NuGet-provided BindingListView doesn't work so I had to find an older version off sourceforge. ( https://sourceforge.net/projects/blw/files/BindingListView/v1.2.0.0/ )

![image](https://user-images.githubusercontent.com/25468624/45267115-446e5c00-b41b-11e8-9958-194de6cb1a06.png)

And now I'm not sure what version of SQLite to get and from where.

**Comment by robbinsrush** [comment]
And yes, I added those packages myself with NuGet when I was unable to build due to these errors.

**Comment by hobomaster22** [comment]
OK that explains what is going on. I downloaded a clean copy and I'm getting the reference issues. I will figure out what's going on and have it fixed soon.

**Comment by hobomaster22** [comment]
Long story short the app I was using added dlls to my global git ignore which caused them to be missed.

Try this branch and hopefully it should build:
https://github.com/hobomaster22/DoomLauncher/tree/bug/release_build

**Comment by robbinsrush** [comment]
Works like a charm! Thank you!

**Comment by hobomaster22** [comment]
Awesome! Merged the branch into master.
